---
title: "chicago_map"
author: "thomas"
date: "10/19/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading package, echo=FALSE, warning=FALSE, include=FALSE}
pacman::p_load(tidyverse, pacman, ggmap, janitor, sf, mapview, leaflet, rgdal, RColorBrewer)
```

```{r Register, loading data, and extracting a random sample, echo=FALSE, warning=FALSE, include=FALSE}
#Register API key to google
register_google(key="AIzaSyBT6yzDKV_DGcFGK9E-cXu0zNUD4WTJOZA")


taxi_trips<-read_csv("Taxi_Trips_-_2020.csv") %>%
  clean_names()

taxi_trips <- na.omit(taxi_trips,cols=c("trip_minutes","trip_miles","trip_total"))

#Sort based on hour of the day
taxi_trips$trip_start=(paste(substr(taxi_trips$trip_start_timestamp,12,13),
                             substr(taxi_trips$trip_start_timestamp,21,22)))

# Creating a new column with simplifies start time of trips
taxi_trips$trip_start[taxi_trips$trip_start == "12 AM"] <- 1
taxi_trips$trip_start[taxi_trips$trip_start == "01 AM"] <- 2
taxi_trips$trip_start[taxi_trips$trip_start == "02 AM"] <- 3
taxi_trips$trip_start[taxi_trips$trip_start == "03 AM"] <- 4
taxi_trips$trip_start[taxi_trips$trip_start == "04 AM"] <- 5
taxi_trips$trip_start[taxi_trips$trip_start == "05 AM"] <- 6
taxi_trips$trip_start[taxi_trips$trip_start == "06 AM"] <- 7
taxi_trips$trip_start[taxi_trips$trip_start == "07 AM"] <- 8
taxi_trips$trip_start[taxi_trips$trip_start == "08 AM"] <- 9
taxi_trips$trip_start[taxi_trips$trip_start == "09 AM"] <- 10
taxi_trips$trip_start[taxi_trips$trip_start == "10 AM"] <- 11
taxi_trips$trip_start[taxi_trips$trip_start == "11 AM"] <- 12
taxi_trips$trip_start[taxi_trips$trip_start == "12 PM"] <- 13
taxi_trips$trip_start[taxi_trips$trip_start == "01 PM"] <- 14
taxi_trips$trip_start[taxi_trips$trip_start == "02 PM"] <- 15
taxi_trips$trip_start[taxi_trips$trip_start == "03 PM"] <- 16
taxi_trips$trip_start[taxi_trips$trip_start == "04 PM"] <- 17
taxi_trips$trip_start[taxi_trips$trip_start == "05 PM"] <- 18
taxi_trips$trip_start[taxi_trips$trip_start == "06 PM"] <- 19
taxi_trips$trip_start[taxi_trips$trip_start == "07 PM"] <- 20
taxi_trips$trip_start[taxi_trips$trip_start == "08 PM"] <- 21
taxi_trips$trip_start[taxi_trips$trip_start == "09 PM"] <- 22
taxi_trips$trip_start[taxi_trips$trip_start == "10 PM"] <- 23
taxi_trips$trip_start[taxi_trips$trip_start == "11 PM"] <- 24

# Rescaling trip duration in minutes and rename it
taxi_trips$trip_seconds <- taxi_trips$trip_seconds / 60
taxi_trips <- rename(taxi_trips, trip_minutes = trip_seconds)

```

```{r Plotting of the map, echo=FALSE, warning=FALSE, include = FALSE}
#Get location of chicago
chicago <- geocode("Chicago, IL")

# function that creates the interactive map
chicago_map <- function(trip_area, data_type, hour){
  if (hour == "day") {
    if (data_type=="trip_miles"){
      label <- "<strong>%s</strong><br/>%g miles"
      tit <- "Trip miles"
      trip_area <- taxi_trips %>%
        select(pickup_community_area, trip_miles) %>%
        mutate(pickup_community_area = as.factor(pickup_community_area),
               trip_miles = (as.numeric(trip_miles))) %>%
        group_by(pickup_community_area) %>%
        summarise(trip_miles = sum(trip_miles))
      plot_trip_area <- rename(trip_area, trip = trip_miles)
    }
    else if (data_type=="trip_minutes"){
      label <- "<strong>%s</strong><br/>%g minutes"
      tit <- "Trip minutes"
      trip_area <- taxi_trips %>%
        select(pickup_community_area, trip_minutes) %>%
        mutate(pickup_community_area = as.factor(pickup_community_area),
               trip_minutes = (as.numeric(trip_minutes))) %>%
        group_by(pickup_community_area) %>%
        summarise(trip_minutes = sum(trip_minutes))
      plot_trip_area <- rename(trip_area, trip = trip_minutes)
    }
    else {
      label <- "<strong>%s</strong><br/>%g$ trip total"
      tit <- "Trip total"
      trip_area <- taxi_trips %>%
        select(pickup_community_area, trip_total) %>%
        mutate(pickup_community_area = as.factor(pickup_community_area),
               trip_total = (as.numeric(trip_total))) %>%
        group_by(pickup_community_area) %>%
        summarise(trip_total = sum(trip_total))
      plot_trip_area <- rename(trip_area, trip = trip_total)
    }
  } 
  else if (data_type=="trip_miles"){
    label <- "<strong>%s</strong><br/>%g miles"
    tit <- "Trip miles"
    trip_area <- taxi_trips %>%
      select(pickup_community_area, trip_miles, trip_start) %>%
      mutate(pickup_community_area = as.factor(pickup_community_area),
             trip_miles = (as.numeric(trip_miles))) %>%
      filter(trip_total==as.numeric(hour)) %>%
      group_by(pickup_community_area) %>%
      summarise(trip_miles = sum(trip_miles))
    plot_trip_area <- rename(trip_area, trip = trip_miles)
  }
  else if (data_type=="trip_minutes"){
    label <- "<strong>%s</strong><br/>%g minutes"
    tit <- "Trip minutes"
    trip_area <- taxi_trips %>%
      select(pickup_community_area, trip_minutes, trip_start) %>%
      mutate(pickup_community_area = as.factor(pickup_community_area),
             trip_minutes = (as.numeric(trip_minutes))) %>%
      filter(trip_total==as.numeric(hour)) %>%
      group_by(pickup_community_area) %>%
      summarise(trip_minutes = sum(trip_minutes))
    plot_trip_area <- rename(trip_area, trip = trip_minutes)
  }
  else {
    label <- "<strong>%s</strong><br/>%g$ trip total"
    tit <- "Trip total"
    trip_area <- taxi_trips %>%
      select(pickup_community_area, trip_total) %>%
      mutate(pickup_community_area = as.factor(pickup_community_area),
             trip_total = (as.numeric(trip_total))) %>%
      filter(trip_total==as.numeric(hour)) %>%
      group_by(pickup_community_area) %>%
      summarise(trip_total = sum(trip_total))
    plot_trip_area <- rename(trip_area, trip = trip_total)
  }
  
  #Make leaflet map with chicago center
  chicago_leaflet <- leaflet() %>% 
    setView(lng=chicago$lon, lat=chicago$lat, zoom=10) %>%
    addProviderTiles(providers$CartoDB.Positron) 
  
  
  #Save chicago areas to use for plotting
  areas <- st_read("chicago_Community_Areas_.geojson", as_tibble=T, quiet=T) %>%
    clean_names() %>%
    select(area_numbe, community, geometry) %>%
    mutate(geometry = st_geometry(geometry),
           area_numbe = as.factor(area_numbe)) %>% #if this stops working extract it to own variable 
    rename(pickup_community_area = area_numbe,
           community_name = community) %>%
    inner_join(plot_trip_area, by="pickup_community_area")
  
  #Trying to color each area by trip
  pal <- colorBin("Blues",bins=4, domain =log10(areas$trip), )
  
  #Generate html labels
  labels <- sprintf(
    label,
    areas$community_name, areas$trip
  ) %>% lapply(htmltools::HTML)
  
  chicago_leaflet <- chicago_leaflet %>%
    addPolygons(data=areas,
                fillColor=~pal(log10(areas$trip)),
                color="lightgrey",
                weight=2,
                fillOpacity=0.8,
                highlightOptions = highlightOptions(
                  weight=3,
                  opacity=2,
                  color="azure1",
                  bringToFront=TRUE),
                label=labels,
                labelOptions=labelOptions(
                  style = list("font-weight" = "normal", padding = "3px 8px"),
                  textsize = "15px",
                  direction = "auto")) %>%
    
    addLegend("bottomright",
              pal = pal,
              values = log10(areas$trip),
              title = tit,
              opacity = 0.8,
              labFormat = leaflet::labelFormat(
                transform = function(x) 10^(x)))
  

  return(chicago_leaflet)
}

```


```{r Defining the UI, echo=FALSE, warning=FALSE}

# Defining the UI
ui <- fluidPage(

  sidebarPanel(
    
    # First input: Type of data
    selectInput(inputId = "data_type",
                label = "Choose the type of data you want to see:",
                choices = list("Trip total" = "trip_total", 
                               "Trip miles" = "trip_miles",
                               "Trip minutes" = "trip_minutes")),
    
    selectInput(inputId = "time",
                label = "Choose the time of day for which you want to see the
                data:",
                choices = list("All day" = "day", "12 AM" = "1", "01 AM" = "2",
                               "02 AM" = "3", "03 AM" = "4", "04 AM" = "5",
                               "05 AM" = "6", "06 AM" = "7", "07 AM" = "8",
                               "08 AM" = "9", "09 AM" = "10", "10 AM" = "11",
                               "11 AM" = "12", "12 PM" = "13", "01 PM" = "14",
                               "02 PM" = "15", "03 PM" = "16", "04 PM" = "17",
                               "05 PM" = "18", "06 PM" = "19", "'07 PM" = "20", 
                               "08 PM" = "21", "09 PM" = "22", "10 PM" = "23",
                               "11 PM" = "24")),
    
  ),
  
  # Main panel for displaying outputs
  mainPanel(
    
    # Hide errors
    tags$style(type = "text/css",
               ".shiny-output-error { visibility: hidden; }",
               ".shiny-output-error:before { visibility: hidden; }"),
    
    # Output: interactive chicago map
    leafletOutput("map1")
    
  )
)

```

```{r Defining the server, echo=FALSE, warning=FALSE}

# Defining the server
server = function(input, output) {
  output$map1 <- renderLeaflet(chicago_map(trip_area,input$data_type ,input$time))
}
```

# Trip data by areas of Chicago

```{r shinyApp, echo=FALSE, warning=FALSE}
shinyApp(ui = ui, server = server)
```


