---
title: "Q1 Attempt"
author: "yiren"
date: "05/10/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(data.table)
library(dplyr)
library(readr)

```


## Previous
```{r}
mytable <- read_csv("data/taxi_trips.csv")
```


```{r cars}
#loading useful packages
pacman::p_load(pacman, party, psych, rio, tidyverse) 
p_load(janitor)

taxi_trips <- import("data/taxi_trips.csv") %>%
  as_tibble() %>%
  clean_names() %>% #from janitor package to remove space from names
  print()


#Extracting random sample
sample <- taxi_trips %>% 
  sample_n(10000) 

# 
# df1 <- sample %>%
#   mutate(pickup_community_area = as.numeric(pickup_community_area)) %>%
#   select(pickup_community_area, trip_total) %>%
#   mutate(trip_total, scale) %>% #standardize c("y", "z"), ~(scale(.) %>% as.vector)
#   group_by(pickup_community_area) %>%
#   arrange(pickup_community_area) %>%
#   summarise(total = sum(trip_total, na.rm=T)) %>%
#   #hist(df1$pickup_community_area, df1$total) 
#   print()
# 
# ?mutate_at  

# min(df1[1], na.rm = T) # 1
# 
# max(df1[1], na.rm = T) # 77 
```

## Dataset

```{r}
head(sample)
```


You can also embed plots, for example:
### 1. Direct Calc w/o Standardization

```{r pressure, echo=FALSE}
sample %>%
  mutate(pickup_community_area = as.numeric(pickup_community_area)) %>%
  select(pickup_community_area, trip_total) 


mytrip = taxi_trips %>%
  mutate(pickup_community_area = as.numeric(pickup_community_area)) %>%
  select(pickup_community_area, trip_total) %>% 
  group_by(pickup_community_area) %>%
  summarise(total = sum(trip_total, na.rm=T)) %>%
  # arrange(desc(total)) %>%
  rename(comm = pickup_community_area) %>% drop_na()


```
It shows community 76 is the one getting most revenue, however, when we look at the area data, community 76 O'Hare is obviously the largest community in Chicago.

### 2. Considering Area
Area data
https://en.wikipedia.org/wiki/Community_areas_in_Chicago#cite_note-CMAP_Area-10

Geospatial Data
https://data.cityofchicago.org/Facilities-Geographic-Boundaries/Boundaries-Community-Areas-current-/cauq-8yn6

Data Cleaning 
```{r}
comm_area = read_csv("data/mywiki.csv")
comm_area_1 = comm_area %>% 
  select(No., `Area(km2)`) %>% 
  rename(comm = No.) %>%
  mutate(comm = as.numeric(comm))
  
```

Join the two dataframes by the community code
```{r}
revenue_area = merge(mytrip, comm_area_1)
revenue_area %>% mutate(standard_rev = total/`Area(km2)`) %>% arrange(desc(standard_rev))
```
just look at data
```{r}
comm_area %>% arrange(desc(`Density(km2)`))
comm_area %>% arrange(desc(Population))
```





